name: fegrow
channels:
  - conda-forge

dependencies:
  - python>=3.8
  - notebook<7.0.0
  - pip
  - rdkit
  - prody
  - openff-toolkit>=0.13
  - parmed
  - openmm>=7.5.0
  - openmm-ml
  - openmmforcefields>=0.14.2 # note 0.12.0-0.14.1 does not allow CMMotionRemover with Custom forces
  - typing-extensions
  - pdbfixer>=1.8.0
  - tqdm
  - openbabel
  - torchani>=2.2.4
  - pytorch>=1.10.0
  - openmm-torch>=0.8
  - pint!=0.2
  - py3dmol>=1.8.0
  - mols2grid>=0.2.4
  - networkx
  - pint-pandas
  - dask
  - dask-jobqueue
  - modal # modAL on pip
  - cachey
  - pyparsing<3.1.0 # temporary fix for prody
